-- MySQL Script generated by MySQL Workbench
-- Mon Apr  6 16:53:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `dropoff_date` DATE NOT NULL,
  `promised_date` DATE NOT NULL,
  `ready_date` DATE NULL,
  `pickup_date` DATE NULL,
  `payment_status` VARCHAR(20) NOT NULL,
  `order_status` VARCHAR(20) NOT NULL,
  `total_items` INT NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `notes` VARCHAR(255) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_customers_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_types` (
  `item_type_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(50) NOT NULL,
  `base_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`item_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_items` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `item_type_id` INT NOT NULL,
  `care_type` VARCHAR(20) NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `line_total` DECIMAL(10,2) NOT NULL,
  `item_status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `fk_order_items_orders_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_items_item_types_idx` (`item_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_item_types`
    FOREIGN KEY (`item_type_id`)
    REFERENCES `mydb`.`item_types` (`item_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendors` (
  `vendor_id` INT NOT NULL AUTO_INCREMENT,
  `vendor_name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `category` VARCHAR(50) NOT NULL,
  `notes` VARCHAR(255) NULL,
  PRIMARY KEY (`vendor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendor_deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendor_deliveries` (
  `delivery_id` INT NOT NULL AUTO_INCREMENT,
  `vendor_id` INT NOT NULL,
  `delivery_date` DATE NOT NULL,
  `supply_name` VARCHAR(100) NOT NULL,
  `quantity` INT NOT NULL,
  `unit_cost` DECIMAL(10,2) NOT NULL,
  `total_cost` DECIMAL(10,2) NOT NULL,
  `notes` VARCHAR(255) NULL,
  PRIMARY KEY (`delivery_id`),
  INDEX `fk_vendor_deliveries_vendors_idx` (`vendor_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendor_deliveries_vendors`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `mydb`.`vendors` (`vendor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
